name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build // Deploy dhaynes.io
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - name: action-yarn
        uses: comchangs/action-yarn@v0.1-beta
      - name: Install Dependencies // yarn
        run: yarn install && yarn run github_build
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
